Added:1d_What_is_UX_Design
Learn-Write-Repeat/UI-UX pull request #11
Opened 2021-07-29 15:22 UTC by sidparashar2001

2021-07-29 17:03 UTC, ishitakapoor26 requested changes

2021-07-29 17:03 UTC, ishitakapoor26 commented on UIUX-1/1.Introduction_to_User_Experience_(UX)_Design/1d_What_is_UX_Design/1d_What_is_UX_Design.md
> +![N|Solid](https://99designs-blog.imgix.net/blog/wp-content/uploads/2020/08/UX_design_principles_jpg_-EtzLc2m.jpg?auto=format&q=60&w=1280&h=720&fit=crop&crop=faces)
Decrease the dimensions of the image, its too big.

2021-07-29 17:03 UTC, ishitakapoor26 commented on UIUX-1/1.Introduction_to_User_Experience_(UX)_Design/1d_What_is_UX_Design/1d_What_is_UX_Design.md
> +![alt text](https://www.creative-tim.com/blog/content/images/wordpress/2020/02/vector-creator-1024x640.jpeg)
Decrease the dimensions over here too . Speaking of presentation of readme file, try to place image on right side and content on left side.

2021-07-31 01:31 UTC, sidparashar2001 commented
Updated @ishitakapoor26

2021-07-31 10:20 UTC, ishitakapoor26 approved these changes

2021-08-25 10:34 UTC, akrish4 approved these changes

2021-08-25 10:34 UTC, merged