update 4a_What_is_Design_Thinking
Learn-Write-Repeat/UI-UX pull request #9
Opened 2021-07-27 03:58 UTC by AfraMP

completed What is Design Thinking

2021-07-27 13:30 UTC, ishitakapoor26 requested changes
Image is still not there and you have to put your files in Intro to UX design folder and then create a folder in it named 4a_What_is_Design_Thinking ; name of md file will be same.

2021-07-28 18:48 UTC, ishitakapoor26 approved these changes

2021-07-29 16:28 UTC, akrish4 approved these changes

2021-07-29 16:29 UTC, akrish4 commented
Nice @AfraMP

2021-07-29 16:29 UTC, merged